name: Checks

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
        - isort
        - flake8
        - pylint
        - bandit
        - package
        - requirements
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install prerequistes for SAML
      if: ${{ matrix.env == 'pylint' }}
      run: |
        sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools tox wheel
    - name: Run ${{ matrix.env }}
      run: tox -e ${{ matrix.env }}
