name: Tests

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  python-django:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.6'
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        django-version:
        - '2.2'
        - '3.2'
        - '4.0'
        exclude:
        - { django-version: '2.2', python-version: '3.10' }
        - { django-version: '4.0', python-version: '3.6' }
        - { django-version: '4.0', python-version: '3.7' }
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install prerequistes for SAML
      run: |
        sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools tox-gh-actions wheel
    - name: Run tests (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }})
      run: tox
      env:
        DJANGO: ${{ matrix.django-version }}
